import React from "react";
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";

import { oneDark } from "react-syntax-highlighter/dist/esm/styles/prism";
import ChartModel from "../assets/ChartModel.png";

export function LinealModelCharts() {
  const code_string =
    "# Hacer una gráfica de dispersión entre los valores\nestimados y los valores reales de prueba\nplt.scatter(y_test, y_pred)\nplt.xlabel('Valor Real')\nplt.ylabel('Valor Estimado (Linear Model)')\nplt.title('Valores Estimados vs. Valores Reales')\nplt.show()";

  return (
    <div>
      <div className="flex flex-wrap justify-between pt-20 sm:pl-20 sm:-m-6">
        <div className="circlePosition w-[200px] h-[200px] left-[20%] absolute bg-[#b41aac] rounded-[100%] z-1 blur-[80px] overflow-x-hidden"></div>
        <div className="relative z-10 hidden w-full lg:w-7/12 xl:w-1/2 sm:block">
          <div className="pr-2 mx-auto -mt-16 max-w-max">
            <div className="flex items-center justify-around">
              <div className="mt-10">
                <SyntaxHighlighter language="python" style={oneDark}>
                  {code_string}
                </SyntaxHighlighter>
                <p className="inline px-3 py-1   mb-5 text-xs font-medium text-gray-50F border-2 rounded-lg font-heading sm:text-sm opacity-40 border-white/10">
                  Python
                </p>
              </div>
            </div>
          </div>
        </div>
        <div className="z-10 w-full p-6 sm:-mt-10 lg:w-5/12 xl:w-1/2">
          <p className="inline px-3 py-1 mb-5 text-xs font-medium text-gray-400 border-2 rounded-lg font-heading sm:text-sm opacity-40 border-white/10">
            Explanation
          </p>
          <div className="max-w-lg text-gray-100 mb-9 sm:text-lg opacity-60">
            <ol>
              <li>1. We will create a plot using matplotlib</li>
            </ol>
            <p>
              <br></br>
              The purpose of this code is to create a scatter plot to visualize
              the relationship between the true target values and the predicted
              target values generated by a linear model. It provides a visual
              representation of how well the model's predictions match the
              actual values.
            </p>
          </div>
        </div>
      </div>
      <div className="flex flex-wrap justify-center">
        <img src={ChartModel} alt="Chart Model" />
      </div>
      
    </div>
  );
}
